[project]
name = "foodakinator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "faiss-cpu>=1.11.0",
    "pandas>=2.3.0",
    "sqlmodel>=0.0.24",
]
